
# pubchem crawler -----------------------------------------------------------

#' @title mda_pubchem_crawler.
#' @description Get compound information according the cid by webchem.
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email{shawnwang2016@@126.com}
#' @param cid_info 'character' or 'data.frame'; For single cid, cid_info equals the pubchem CID, For multiple cid, cid_info is a dataframe generated from mda_get_cid.
#' @param type "single','multiple';  For one compound or multiple compounds.
#' @param multi_core 'TRUE' or 'FALSE'; Run web crawler with multicore or not. 
#' @return pubchem_item An data frame about stored the pubchem information of input cids.
#' @importFrom webchem pc_prop
#' @importFrom dplyr mutate 
#' @importFrom magrittr %>%
#' @importFrom future plan
#' @importFrom furrr future_map_dfr
#' @references See webchem https://github.com/ropensci/webchem.
#' @export
#' @examples  
#' \dontrun{
#' # import file
#' xx <- read.csv("cd_result.csv")
#' # data orgnazation
#' orz_data = mda_data_org(compound_info = xx, source = "CD")
#' # Get cid (batch)
#' name2cid = mda_get_cid(data_info = orz_data)
#' # please wait for a while
#' pubchem_detail = mda_pubchem_crawler(cid_info = name2cid,type = "multiple",multi_core = T)
#' }

mda_pubchem_crawler = function(cid_info,type = "multiple",multi_core = TRUE) {
  ## rebulid pc_prop for purrr or furrr
  pc_prop_progress = function(cid) {
    a =  webchem::pc_prop(cid = cid,properties = c("MolecularFormula", "MolecularWeight","InChIKey", 
                                                   "IUPACName","ExactMass"))
    return(a)
  }
  ## run
  if (type == "single" & length(cid_info) == 1) {
    tmp_cid_char = cid_info
    tmp_pubchem = webchem::pc_prop(cid = tmp_cid_char,properties = c("MolecularFormula", "MolecularWeight","InChIKey", 
                                                                     "IUPACName","ExactMass"))
    return(tmp_pubchem)
  } else if (type == "multiple") {
    future::plan("multisession")
    tryCatch(
      {print("Start catching information from pubchem, this may take a long time please wait.")
      tmp_cid_char = unique(cid_info$cid)
      tmp_pubchem = future_map_dfr(tmp_cid_char,pc_prop_progress,.progress = T) %>% 
        mutate(CID = as.character(CID))
      return(tmp_pubchem)},
      error = function(x) {
        cat("Error in querys, please checke the cid_info, for multiple cids, this data sholud be generated by 'mda_get_cid'.")
      }
    )
  } else {
    cat("Wrong parameters, please check carefully!")
  }
}


#' @title mda_pubchem_crawler_sh.
#' @description Get compound information according the cid by webchem.
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email{shawnwang2016@@126.com}
#' @param cid 'character'; pubchem cid
#' @return pubchem_item An data frame about stored the pubchem information of input cids.
#' @importFrom  webchem pc_prop
#' @references See webchem https://github.com/ropensci/webchem.


mda_pubchem_crawler_sh = function(cid) {
  a = tibble(
    CID = cid,
    MolecularFormula = NA,
    MolecularWeight = NA,
    InChIKey = NA,
    IUPACName = NA,
    ExactMass =NA,
  )
  tryCatch({
    a = webchem::pc_prop(cid = cid,properties = c("MolecularFormula", "MolecularWeight","InChIKey", 
                                                  "IUPACName","ExactMass"))},error = function(e) {
    }
  )
  if (is.na(a$MolecularFormula[1])) {message(paste(a$CID[1],"failed to match pubchem!\n"))} else {
    message(paste(a$query[1],"success to match pubchem!\n"))
  }
  return(a)
}


