
# Classification  -----------------------------------------------------------


#' @title mda_classfire.
#' @description Compound classification via classyfireR
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email{shawnwang2016@@126.com}
#' @param query 'character' or 'data.frame'; For single InChiKey, query equals the InChiKey, For multiple InChiKeys, query is a data frame from mda_pubchem_crawler.
#' @param type "single','multiple';  For one compound or multiple compounds.
#' @return pubchem_item An data frame about stored the pubchem information of input cids.
#' @importFrom dplyr select mutate bind_rows as_tibble
#' @importFrom tidyr pivot_wider drop_na
#' @importFrom magrittr %>%
#' @importFrom purrr map map_df
#' @import classyfireR
#' @references See classyfireR https://github.com/aberHRML/classyfireR
#' @export
#' @examples  
#' \dontrun{
#' # import file
#' xx <- read.csv("cd_result.csv")
#' # data orgnazation
#' orz_data = mda_data_org(compound_info = xx, source = "CD")
#' # Get cid (batch)
#' name2cid = mda_get_cid(data_info = orz_data)
#' # please wait for a while
#' pubchem_detail = mda_pubchem_crawler(cid_info = name2cid,type = "multiple",multi_core = T)
#' pubchem_class = mda_classfire(query = pubchem_detail,type = "multiple")
#' }

mda_classfire = function(query,type = "multiple") {
  ## rebuild function for purrr 
  shawn_get_classification = function(id){
    Sys.sleep(0.1)
    get_classification(inchi_key = id)
  }
  ## convert classyfireR result to tbl
  classfireR2tbl = function(x){
    # make a black df
    if (is.null(x)) {
      tmp_x = data.frame(
        InchIkeys = NA,
        Level = NA,
        Classification = NA
      ) %>% as_tibble()
    } else if(is.null(x@meta$inchikey)) {  # make na values as blank
      tmp_x = data.frame(
        InchIkeys = NA,
        Level = NA,
        Classification = NA)
    } else {
      tmp_x = classification(x) %>% 
        mutate(InchIkeys = gsub("InChIKey=","",meta(x)$inchikey)) %>% 
        select(InchIkeys,Level,Classification)
    }
    return(tmp_x)
  }
  # run
  if(type == "single" & length(query) == 1) {
    InchIKeys = query
  } else {
    InchIKeys = query$InChIKey
  }
  tryCatch(
    {
      cat("Start processsing...")
      classification_list = map(InchIKeys,shawn_get_classification)
      # convert as classyfireR2tbl
      result_tbl = purrr::map_df(classification_list,classfireR2tbl)
      # convert long table to wide table
      class_out = bind_rows(result_tbl) %>% 
        drop_na() %>% unique() %>% 
        pivot_wider(names_from = Level,values_from = Classification) 
      return(class_out)
    },error = function(e) {
      cat("Please check internet connection!")
    }
  )
}


#' @title classfireR2tbl
#' @description merge classyfireR result
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email{shawnwang2016@@126.com}
#' @param x 'character' ; result of shawn_get_classification
#' @return pubchem_item An data frame about stored the pubchem information of input cids.
#' @importFrom dplyr select mutate
#' @importFrom tidyr pivot_wider drop_na
#' @importFrom magrittr %>%
#' @importFrom purrr map map_df
#' @references See classyfireR https://github.com/aberHRML/classyfireR
#' @export
classfireR2tbl = function(x){
  # make a black df
  if (is.null(x)) {
    tmp_x = data.frame(
      InchIkeys = NA,
      Level = NA,
      Classification = NA
    ) %>% as_tibble()
  } else if(is.null(x@meta$inchikey)) {  # make na values as blank
    tmp_x = data.frame(
      InchIkeys = NA,
      Level = NA,
      Classification = NA)
  } else {
    tmp_x = classification(x) %>% 
      mutate(InchIkeys = gsub("InChIKey=","",meta(x)$inchikey)) %>% 
      select(InchIkeys,Level,Classification)
  }
  return(tmp_x)
}


# Table merge  -----------------------------------------------------------


#' @title mda_merge_info
#' @description Merge all information.
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email {shawnwang2016@@126.com}.
#' @param orz_data 'dataframe'; generated by function mda_data_org.
#' @param name2cid 'dataframe'; generated by function mda_get_cid.
#' @param pubchem_detail 'dataframe'; generated by function mda_pubchem_crawler.
#' @param pubchem_class 'dataframe'; generated by function mda_classfire.
#' @return pubchem_item An data frame about stored the pubchem information of input cids.
#' @importFrom dplyr mutate left_join right_join relocate
#' @importFrom tidyr pivot_wider drop_na
#' @importFrom magrittr %>%
#' @export
#' @examples 
#' \dontrun{
#' # import file
#' xx <- read.csv("cd_result.csv")
#' # data orgnazation
#' orz_data = mda_data_org(compound_info = xx, source = "CD")
#' # Get cid (batch)
#' name2cid = mda_get_cid(data_info = orz_data)
#' # please wait for a while
#' pubchem_detail = mda_pubchem_crawler(cid_info = name2cid,type = "multiple",multi_core = T)
#' pubchem_class = mda_classfire(query = pubchem_detail,type = "multiple")
#' final_tbl = mda_merge_info(orz_data,name2cid,pubchem_detail,pubchem_class)
#' }

mda_merge_info = function(orz_data,name2cid,pubchem_detail,pubchem_class,CTS_kegg){
  name2cid$cid = as.character(name2cid$cid)
  pubchem_detail$CID = as.character(pubchem_detail$CID)
  result_out = name2cid %>% 
    left_join(.,pubchem_detail,by = c("cid" = "CID") )%>% 
    left_join(.,pubchem_class,by = c("InChIKey"="InchIkeys")) %>% 
    right_join(.,orz_data,by = c("query" = "name") ) %>% 
    left_join(CTS_kegg,by = c("InChIKey" = "InChIkey")) %>% 
    mutate(
      MolecularFormula = gsub(" ","",MolecularFormula),
      MolecularWeight = as.numeric(MolecularWeight),
      mw = as.numeric(mw),
      Check_MF = case_when(
        mf == MolecularFormula ~ TRUE,
        TRUE ~ FALSE
      ),
      Check_MW = case_when(
        abs(mw - MolecularWeight) <= 5 ~  TRUE,
        TRUE ~ FALSE
      ),
      High_identical = case_when(
        Check_MF == TRUE & Check_MW == TRUE ~ TRUE,
        TRUE ~ FALSE
      )
    ) %>% 
    distinct() %>% 
    relocate(compound_id,.before = query) %>% 
    as.data.frame()
  
  return(result_out)
}


#' @title mda_tbl_merge
#' @description Merge two tables for shinyapp
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email {shawnwang2016@@126.com}.
#' @param tbl1 'dataframe'; table1.
#' @param tbl2 'dataframe'; table2.
#' @param col1 'character'; Key column name for table1.
#' @param col2 'character'; Key column name for table2.
#' @param method 'character'; left_join, right_join, inner_join or full_join.
#' @references https://github.com/gadenbuie/tidyexplain#relational-data
#' @importFrom dplyr mutate left_join right_join inner_join full_join
#' @importFrom magrittr %>%
#' @export
#' @examples  
#' \dontrun{
#' newtbl = mda_tbl_merge(tbl1 = orz_data,tbl2 = name2cid,col1 = "query",col2 = "name")
#' }


mda_tbl_merge = function(tbl1,tbl2,col1,col2,method) {
  if (method == "left") {
    tbl_out = left_join(tbl1,tbl2,by = c(col1 = col2)) 
    return(tbl_out)
  } else if(method == "right") {
    tbl_out = right_join(tbl1,tbl2,by = c(col1 = col2))
    return(tbl_out)
  } else if(method == "inner") {
    tbl_out = inner_join(tbl1,tbl2,by = c(col1 = col2))
    return(tbl_out)
  } else if(method == "full") {
    tbl_out = full_join(tbl1,tbl2,by = c(col1 = col2))
    return(tbl_out)
  } else {
    cat("Please check your input, pay attention to case sensitivity!")
  }
}



