#' @title DAM_analysis
#' @description Different accumulation analysis
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email{shawnwang2016@@126.com}
#' @param x 'Dataframe' or 'matrix'; Peak area file contains all sample.
#' @param left_index 'characters'; The first sample set names corresponding to the peak area matrix
#' @param right_index 'characters'; The second sample set names corresponding to the peak area matrix
#' @param left 'characters'; The group name of first sample
#' @param right 'characters'; The group name of first sample
#' @param method 'characters'; t-test， wilcox-test. default is t-test.
#' @param method2 'characters'; pls-da or opls-da. default is opls-da. By default, 7-fold cross validation were used followed by ropls, if sample size is less than 7, use LOOCV method.
#' @param method3 'characters'; method for adjust p value, see p.adjust.methods
#' @param paired 'logical'; paired t-test/wilcox_test or not; default = FASLE
#' @return A list; MDA_tbl is a dataframe contains all compounds and all DAM judge values include log2fc,pvalue,VIP and FDR. opls_out is opls_da class generated by ropls package.
#' @importFrom dplyr select mutate group_by summarise arrange distinct
#' @importFrom tidyr replace_na nest unnest
#' @importFrom purrr map2_chr
#' @importFrom crayon green red blue yellow
#' @importFrom ropls opls getVipVn 
#' @importFrom rstatix t_test wilcox_test
#' @importFrom stringr str_pad str_split
#' @export
#' @examples 
#' \dontrun{
#' #> For mass_dataset
#' mat = object %>% extract_expression_data() %>% rownames_to_column("variable_id")
#' sample_info = object %>% extract_sample_info()
#' left = "case"
#' right = "control"
#' left_index = sample_info %>% filter(group == left) %>% pull(sample_id)
#' right_index = sample_info %>% filter(group == right) %>% pull(sample_id)
#' res.case_vs_control = DAM_analysis(
#'   x = mat,
#'   left = left,
#'   right = right,
#'   left_index = left_index,
#'   right_index = right_index,
#'   method = "wilcox_test",
#'   method2 = "opls-da",
#'   method3 = "fdr",
#'   paired = FALSE
#' )
#' 
#' #> for peak picking table 
#' #> generate a in-silico metabolomics expression matrix
#' base_expression <- matrix(rnorm(1000, mean = 10, sd = 3), nrow = 1000, ncol = 1)
#' group1_variability <- matrix(rnorm(3000, mean = 0, sd = 0.5), nrow = 1000, ncol = 3)
#' group2_variability <- matrix(rnorm(3000, mean = 0, sd = 0.5), nrow = 1000, ncol = 3)
#' mat <- cbind(base_expression + group1_variability, base_expression + group2_variability)
#' colnames(mat) = paste0("sample_0",c(1:6))
#' rownames(mat) = paste0("compound_",c(1:1000))
#' left_index = c("sample_01","sample_02","sample_03")
#' right_index = c("sample_04","sample_05","sample_06")
#' left = "case"
#' right = "control"
#' 
#' res.case_vs_control = DAM_analysis(
#'   x = mat,
#'   left = left,
#'   right = right,
#'   left_index = left_index,
#'   right_index = right_index,
#'   method = "wilcox_test",
#'   method2 = "opls-da",
#'   method3 = "fdr",
#'   paired = FALSE
#' )
#' }

DAM_analysis = function(x,left_index,right_index,left,right,
                       method=c('t-test','wilcox-test'),
                       method2 = c("opls-da",'pls-da'),
                       method3 = p.adjust.methods,
                       paired = FALSE){
  ##> args
  method = match.arg(method)
  method2 = match.arg(method2)
  method3 = match.arg(method3)
  ##> msg setting
  msg_yes = green$bold$italic
  msg_no = red$bold$italic
  msg_run = blue$bold$italic$underline
  msg_warning = yellow$bold$italic
  ##>left index
  l_num = length(left_index);
  r_num = length(right_index)
  ##> check bio rep numbers
  if(l_num > 10000 | l_num > 10000) {
    message(msg_no("emmmm.... are you sure you have more than 10,000 biological replicates!? "))
    q(status = 1)
  }

  if(l_num < 2 | r_num < 2) {
    message(msg_no(paste0("ERROR: ",left," or ",right," has only one biological repeat. It is not possible to do pairwised t-test! \nplease remove the corresponding samples from both peak file and group file.")))
    q(status = 1)
  } 
  ##> 1st column to rownumber
  if(is.character(x[[1]])) {
    colnames(x)[1] = "CompoundID"
    mat = x %>% 
      column_to_rownames("CompoundID") %>% 
      select(all_of(left_index),all_of(right_index)) %>% 
      distinct()
  } else {mat = x}
  ##> convert into numeric data
  mat <- 
    mat %>% dplyr::mutate(across(everything(),as.numeric))
  if(any(is.na(mat))) {
    message(msg_warning(paste0("warning: detected non-numeric or NA in your matrix, make sure your expression data have been normalized.")))
  }

  colnames(mat) = c(paste0("left","_",str_pad(c(1:l_num), 4,side = "left", "0")),
                    paste0("right","_",str_pad(c(1:r_num), 4,side = "left", "0")))
  
  mean_mat = mat %>% 
    rownames_to_column("CompoundID") %>% 
    pivot_longer(!CompoundID,names_to = "Sample",values_to = "Peak") %>% 
    mutate(Sample = str_split(Sample,"_",2,T)[,1]) %>% 
    group_by(CompoundID,Sample) %>% 
    summarise(mean = mean(Peak),.groups = "drop_last") %>% 
    pivot_wider(names_from = Sample,values_from = mean)
  
  # DAM test
  
  if (method == "t-test") {
    mat %>%
      rownames_to_column("CompoundID") %>%
      pivot_longer(!CompoundID,names_to = "Sample",values_to = "Peak") %>%
    mutate(Sample = str_split(Sample,"_",2,T)[,1]) %>% 
      group_by(CompoundID) %>%
      t_test(Peak ~ Sample,detailed = TRUE,paired = paired) %>% 
      dplyr::select(CompoundID,p)-> Diff_result_all
  } else if(method =="wilcox-test") {
    mat %>%
      rownames_to_column("CompoundID") %>%
      pivot_longer(!CompoundID,names_to = "Sample",values_to = "Peak") %>%
      mutate(Sample = str_split(Sample,"_",2,T)[,1]) %>% 
      group_by(CompoundID) %>%
      wilcox_test(Peak ~ Sample,detailed = TRUE,paired = paired) %>% as.data.frame() %>% 
      dplyr::select(CompoundID,p)-> Diff_result_all
  } 
  
  ##> 计算FDR
  Diff_result_all$FDR = p.adjust(p = Diff_result_all$p,method = method3,n = nrow(Diff_result_all))
  
  if((l_num + r_num)<=6) {crossv = (l_num + r_num); message(msg_warning(paste0("Warning: Sample number less than 7 by ropls package required. It is impossible to use 7-fold crossValidation, use ",crossv,"-fold crossval instead (LOOCV).")))} else {crossv = 7}
  
  run_pls = function(mat) {
    tmp_x = NULL
    tryCatch({
      if(method2 == "pls-da") {
        tmp_x = ropls::opls(
          x = mat %>% t(),
          y = data.frame(
            row.names = colnames(mat),
            group = rep(c(left,right),times = c(l_num,r_num))
          ) %>% as.matrix(),
          crossvalI = crossv)
      } else if (method2 == "opls-da") {
        tmp_x = tryCatch({
          ropls::opls(
            x = mat %>% t(),
            y = data.frame(
              row.names = colnames(mat),
              group = rep(c(left,right),times = c(l_num,r_num))
            ) %>% as.matrix(),
            orthoI = NA,
            predI = 1,
            crossvalI = crossv
          )
        },error = function(e) {
          ropls::opls(
            x = mat %>% t(),
            y = data.frame(
              row.names = colnames(mat),
              group = rep(c(left,right),times = c(l_num,r_num))
            ) %>% as.matrix(),
            orthoI = 1,
            predI = 1,
            crossvalI = crossv
          )
        })
      }
    }, error = function(e) {
      print("pls-da failed")
    }
    )
    return(tmp_x)
  }
  
  opls_da = run_pls(mat)
  
  if(is.null(opls_da)) {
    Diff_result_clean = data.frame(
      CompoundID = Diff_result_all$CompoundID,
      left = mean_mat$left,
      right = mean_mat$right,
      pvalue = Diff_result_all$p,
      FDR = Diff_result_all$FDR,
      VIP = 0
    )  %>% 
      mutate(log2fc = log2(left/right))
    colnames(Diff_result_clean)[c(2,3)] = c(left,right)
  } else {
    VIP= ropls::getVipVn(opls_da) %>% as.data.frame() %>% setNames('VIP') %>% 
      rownames_to_column("CompoundID")
    Diff_result_all <- 
      Diff_result_all %>% 
      left_join(.,VIP,by = "CompoundID")
    Diff_result_clean = data.frame(
      CompoundID = Diff_result_all$CompoundID,
      left = mean_mat$left,
      right = mean_mat$right,
      pvalue = Diff_result_all$p,
      FDR = Diff_result_all$FDR,
      VIP = Diff_result_all$VIP
    )  %>% 
      mutate(log2fc = log2(left/right))
    colnames(Diff_result_clean)[c(2,3)] = c(left,right)
  }
  Diff_result_clean <-
    Diff_result_clean %>% 
    mutate(
      log2fc = case_when(
        log2fc == Inf ~ 10,
        log2fc == -Inf ~ -10,
        TRUE ~ log2fc
      )
    )
  
  ## get vip
  outfile = list(
    DAM_tbl = Diff_result_clean,
    opls_out = opls_da
  )
  
  return(outfile)
}
