#' @title DM_analysis
#' @description Different accumulation analysis
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email{shawnwang2016@@126.com}
#' @param x 'Dataframe' or 'matrix'; Peak area file contains all sample.
#' @param left_index 'characters'; The first sample set names corresponding to the peak area matrix
#' @param right_index 'characters'; The second sample set names corresponding to the peak area matrix
#' @param left 'characters'; The group name of first sample
#' @param right 'characters'; The group name of first sample
#' @return A list; MDA_tbl is a dataframe contains all compounds and all DAM judge values include log2fc,pvalue,FDR and FDR. opls_out is opls_da result generated by ropls package.
#' @importFrom dplyr select mutate group_by summarise arrange
#' @importFrom tidyr replace_na nest unest
#' @importFrom purrr map2_chr
#' @importFrom crayon green red blue yellow
#' @importFrom ropls opls getVipVn
#' @export
#' @examples 
#' \dontrun{
#' # set param
#' mat = step7_result %>% select("Compound_ID",starts_with("sample")) %>% as.matrix
#' left_index = c("sample_01","sample_02","sample_03")
#' right_index = c("sample_04","sample_05","sample_06")
#' left = "case"
#' right = "control"
#' DM_analysis(x = mat,left_index,right_index,left,right)
#' }
DM_analysis = function(x,left_index,right_index,left,right){
  msg_yes = green$bold$italic
  msg_no = red$bold$italic
  msg_run = blue$bold$italic$underline
  msg_warning = yellow$bold$italic
  l_num = length(left_index);
  r_num = length(right_index)
  if(l_num < 2 | r_num < 2) {
    message(msg_no(paste0("ERROR: ",left," or ",right," has only one biological repeat. It is not possible to do pairwised t-test! \nplease remove the corresponding samples from both peak file and group file.")))
    q(status = 1)
  } 
  mat = x %>% 
    column_to_rownames("CompoundID") %>% 
    select(all_of(left_index),all_of(right_index))
  colnames(mat) = c(paste0("left","_",str_pad(c(1:l_num), 3,side = "left", "0")),
                    paste0("right","_",str_pad(c(1:r_num), 3,side = "left", "0")))
  mean_mat = mat %>% 
    rownames_to_column("CompoundID") %>% 
    pivot_longer(!CompoundID,names_to = "Sample",values_to = "Peak") %>% 
    mutate(Sample = gsub("....$","",Sample)) %>% 
    group_by(CompoundID,Sample) %>% 
    summarise(mean = mean(Peak),.groups = "drop_last") %>% 
    pivot_wider(names_from = Sample,values_from = mean)
  # get.Test
  mat %>% 
    rownames_to_column("CompoundID") %>% 
    pivot_longer(!CompoundID,names_to = "Sample",values_to = "Peak") %>% 
    mutate(Sample = gsub("....$","",Sample)) %>% 
    group_by(CompoundID,Sample) %>% 
    nest() %>% 
    spread(key = Sample,value = data) %>% 
    mutate(
      t_test = map2(
        .x = left,
        .y = right,
        .f =  ~{t.test(.x$Peak, .y$Peak) %>% broom::tidy()}
      ),
      log2fc = map2(
        .x = left,
        .y = right,
        .f = ~{log2(mean(.x$Peak)/mean(.y$Peak))}
      )
    ) %>% 
    unnest(cols = -CompoundID,names_repair = "unique") %>% 
    select(-contains("Peak")) %>% 
    unique() -> Diff_result_all
  Diff_result_all$FDR = p.adjust(p = Diff_result_all$p.value,method = "BH",n = nrow(Diff_result_all))
  if((l_num + r_num)<=6) {crossv = (l_num + r_num); message(msg_warning(paste0("Warning: Sample number less than 7 by ropls package required. It is impossible to use 7-fold crossValidation, use ",crossv,"-fold crossval instead.")))} else {crossv = 7}
  opls_da = ropls::opls(
    x = mat %>% t(),
    y = data.frame(
      row.names = colnames(mat),
      group = rep(c(left,right),times = c(l_num,r_num))
    ) %>% as.matrix(),crossvalI = crossv
  )
  
  VIP= ropls::getVipVn(opls_da) %>% as.data.frame()
  Diff_result_all$VIP = VIP$.
  Diff_result_clean = data.frame(
    CompoundID = Diff_result_all$CompoundID,
    left = mean_mat$left,
    right = mean_mat$right,
    log2fc = Diff_result_all$log2fc,
    pvalue = Diff_result_all$p.value,
    FDR = Diff_result_all$FDR,
    VIP = Diff_result_all$VIP
  ) 
  colnames(Diff_result_clean)[c(2,3)] = c(left,right)
  ## get vip
  outfile = list(
    DAM_tbl = Diff_result_clean,
    opls_out = opls_da
  )
  return(outfile)
}
