#' @title DM_report
#' @description Get kegg cid by CTS
#' @author Shawn Wang <http://www.shawnlearnbioinfo.top>.
#' \email{shawnwang2016@@126.com}
#' @param working_dir 'characters'; working dir path.
#' @param peak_path 'characters'; peak matrix name
#' @param group_path 'characters'; group file name
#' @param annotation_path 'characters'; annotation_file
#' @param left 'characters'; The group name of first sample
#' @param right 'characters'; The group name of first sample
#' @param pval_cut 'numeric'; pvalue cutoff from 0-1, default = 0.05
#' @param qval_cut 'numeric'; qvalue (FDR) cutoff from 0-1, default = 0.05
#' @param VIP_cut 'numeric'; VIP of opls-da or pls-da cutoff, default = 1
#' @param log2fc_cut numeric'; log2(foldchange) cutoff, default = 0
#' @return A list; MDA_tbl is a dataframe contains all compounds and all DAM judge values include log2fc,pvalue,FDR and FDR. opls_out is opls_da result generated by ropls package.
#' @importFrom dplyr select mutate group_by summarise arrange
#' @importFrom tidyr replace_na nest unest
#' @importFrom purrr map2_chr
#' @importFrom crayon green red blue yellow
#' @importFrom ropls opls getVipVn
#' @importFrom PCAtools pca biplot
#' @import plotly
#' @import ggplot2
#' @export 
DAM_report = function(working_dir = "./",peak_path,group_path,annotation_path,left,right,pval_cut = 0.05,qval_cut = 1,VIP_cut = 1,log2fc_cut = 0,Interactive = TRUE) {
  Interactive = Interactive
  msg_yes = green$bold$italic
  msg_no = red$bold$italic
  msg_run = blue$bold$italic$underline
  msg_warning = yellow$bold$italic
  ## set working direction
  setwd(working_dir)
  file_type = str_extract(string = peak_path,pattern = "....$")
  group_type = str_extract(string = group_path,pattern = "....$")
  annot_type = str_extract(string = annotation_path,pattern = "....$")
  store_path = paste0("./",left,"_vs_",right) %>% gsub(" ","",.)
  dir.create(path = store_path,showWarnings = FALSE)
  rmarkdown::draft(
    file = "MAD_report",
    template = "mad-report",
    package = "MDAtoolkits",
    edit = FALSE
  )
  ## get peak area file ==============
  message(msg_run("Step1. File format check ... "))
  if (file_type == ".csv") {
    peak_raw = read.csv(peak_path) %>% rename_with(.cols = 1,~ "CompoundID")
  } else {
    peak_raw = read.delim(peak_path,header = T,sep = "\t",quote = NULL) %>% rename_with(.cols = 1,~ "CompoundID")
  }
  ## check whether chr in peak file
  peak_check = peak_raw %>% pivot_longer(
    !CompoundID,names_to = "sample",values_to = "peak"
  )
  check_tmp1 = class(peak_check$peak)
  if (check_tmp1 != "numeric") {
    suppressWarnings({
      check_tmp2 = peak_check %>% 
        mutate(peak = as.numeric(peak)) %>% 
        filter(is.na(peak))
    })
    
    error_compound = unique(check_tmp2$CompoundID)
    message(msg_no("Peak file check: Failed! The following cells has non-numeric charaters!\n",paste0(capture.output(as.data.frame(check_tmp2)), collapse = "\n")))
  #  q(status = 1)
    
  }
  
  ## check sample number
  if(ncol(peak_raw)< 4) {
    message(msg_no("Peak file check: Failed! \nSample number smaller than 4, we need at least two samples, each sample have at least two biological repeats!"))
  #  q(status = 1)
  }
  ## NA value check
  NA_check =  nrow(peak_raw[is.na(peak_raw[,-1]),-1])
  if (NA_check == 0) {
    message(msg_yes("Peak file check: Pass!"))
  } else {
    message(msg_no("Peak file check: Failed! \nNA value was not allowed in peak area matrix, please check your input file!"))
  #  q(status = 1)
  }
  
  ##  get group file =========
  if (group_type == ".csv") {
    group_df = read.csv(group_path) %>% rename_with(.cols = c(1,2),~ c("Sample","Group")) %>% 
      mutate(Group = gsub("^ ","",Group)) %>% mutate(Group = gsub(" $","",Group))
  } else {
    group_df = read.delim(group_path,header = T,sep = "\t",quote = NULL) %>% rename_with(.cols = c(1,2),~ c("Sample","Group")) 
  }
  ## check sample number
  if(ncol(group_df) != 2) {
    message(msg_no("Group file check: Failed! \nGroup file ONLY allowed two columns, \n   1. the 1st column is sampleIDs correspounding to the normalization peak file.\n   2. the 2nd column is group labels of the samples."))
  #  q(status = 1)
  }
  ## NA value check
  NA_check =  nrow(group_df[is.na(group_df),-1])
  if (is.null(NA_check)) {
    message(msg_yes("Group file check: Pass!" ))
  } else {
    message(msg_no("Group file check: Failed! \nBlank was not allowed in input file, maybe at the bottom of the input file have blank rows, remove them under softwares like textmate or vscode not recommand in excel, please check your input file!"))
  #  q(status = 1)
  }
  
  if(isFALSE(left %in% group_df$Group) | isFALSE(right %in% group_df$Group)) {
    unlink(store_path, recursive = TRUE)
    message(msg_no("Error: Wrong group labels, please check the prameter\n<-a ...> and <-b ...>"))
  #  q(status = 1)
  }
  
  ##  get annotation file =========
  if (annot_type == ".csv") {
    annot_df = read.csv(annotation_path) %>% rename_with(.cols = 1,~ c("CompoundID"))
  } else {
    annot_df = read.delim(annotation_path,header = T,sep = "\t",quote = NULL) %>% rename_with(.cols = 1,~ c("CompoundID"))
  }
  ## check sample number
  if(ncol(annot_df) < 2) {
    message(msg_no("Compound annotation file should be more than two columns, with the 1st column as Compound ID. Please check your file"))
  #  q(status = 1)
  } else {
    message(msg_yes("Annotation file check: Pass!" ))
  }
  
  
  # PCA analysis ------------------------------------------------------------
  
  message(msg_run("Step2. Start PCA analysis ..."))
  
  left_index = group_df %>% 
    filter(Group == left) %>%
    select(Sample) %>% 
    .$Sample
  l_num = length(left_index)
  right_index = group_df %>% 
    filter(Group == right) %>%
    select(Sample) %>% 
    .$Sample
  r_num = length(right_index)
  pca_mat = peak_raw %>% 
    column_to_rownames("CompoundID") %>% 
    select(all_of(left_index),all_of(right_index))
  
  colnames(pca_mat) = c(paste0(left,"_rep",str_pad(string = c(1:l_num),width = 2,side = "left",pad = "0")),
                        paste0(right,"_rep",str_pad(string = c(1:r_num),width = 2,side = "left",pad = "0"))) %>% gsub(" ","",.)
  
  pca_group = data.frame(
    row.names = colnames(pca_mat),
    group = rep(c(left,right),times = c(l_num,r_num))
  )
  
  message(msg_run("running pca."))
  pca_result = pca(
    mat = pca_mat,
    metadata = pca_group,
    scale = T,removeVar = 0.1
  )
  if(sum(l_num,r_num) < 20) {p_size = 3} else {p_size = 1} 
  
  message(msg_run("running biplot"))
  
  pdf(file = paste0(store_path,"/01.PCA1.pdf"),height = 8,width = 8)
  suppressMessages(
    biplot(
      pcaobj = pca_result,
      colby = "group",
      hline = 0,vline = 0,pointSize = p_size,
      title = "biplot",
      subtitle = paste0(left, " vs " ,right),encircle = T,legendPosition = "top"
    )
  )
  
  invisible(dev.off())
  pdf(file = paste0(store_path,"/01.PCA_clean.pdf"),height = 8,width = 8)
  biplot(
    pcaobj = pca_result,
    colby = "group",
    hline = 0,vline = 0,lab = "",legendPosition = "top",pointSize = p_size
  )
  invisible(dev.off())
  if(is.null(pca_result)) {
   ## q(status = 1)
  } else {
    message(msg_yes(paste0("Congratulation PCA analysis done! \nplease change directory to \n",getwd(),gsub("./","/",store_path),"\nchecking the result.")))
  }
  
  # DAM analysis ------------------------------------------------------------
  message(msg_run("Step3. Start DAM analysis ... "))
  
  message(msg_run("Pairwised t-test ..."))
  DAM_all = DM_analysis(
    x = peak_raw,
    left_index = left_index,
    right_index = right_index,
    left = left,
    right = right
  )
  
  message(msg_run("opls-DA ..."))
  ## output opls-da figure
  # pdf(paste0(store_path,"/01.opls_da_result.pdf"),width = 10,height = 10)
  # plot(DAM_all$opls_out,parPaletteVc = c("purple", "gold"))
  # invisible(dev.off())
  
  DAM_tbl_all = DAM_all$DAM_tbl
  DAM_tbl_all.anno = DAM_tbl_all %>%
    left_join(.,annot_df,by = "CompoundID")
  write.csv(x = DAM_tbl_all,file = paste0(store_path,"/02.All_compound_DAM_result.csv"),row.names = F)
  write.csv(x = DAM_tbl_all.anno,file = paste0(store_path,"/02.All_compound_DAM_result_annotation.csv"),row.names = F)
  
  message(msg_run("Upset plot..."))
  ## upset plot
  
  FvsH_upset = DAM_tbl_all %>% 
    mutate(
      log2fc = case_when(
        abs(log2fc) >= 1 ~ 1,
        TRUE ~ 0
      ),
      pvalue = case_when(
        pvalue <= 0.05 ~ 1,
        TRUE ~ 0
      ),
      FDR = case_when(
        FDR <= 0.05 ~ 1,
        TRUE ~ 0
      ),
      VIP = case_when(
        VIP >= 1 ~ 1,
        TRUE ~ 0
      )
    ) %>% 
    column_to_rownames("CompoundID") %>% 
    as.matrix()
  
  m = make_comb_mat(FvsH_upset)
  ss = set_size(m)
  cs = comb_size(m)
  
  ht = UpSet(
    m,
    set_order = order(ss),
    comb_order = order(comb_degree(m), -cs),
    top_annotation = HeatmapAnnotation(
      "DM Intersections" = anno_barplot(
        cs,
        ylim = c(0, max(cs)*1.1),
        border = FALSE, 
        gp = gpar(fill = "salmon",alpha = 0.6), 
        height = unit(4, "cm")
      ),
      annotation_name_side = "left", 
      annotation_name_rot = 90
    ),
    left_annotation = rowAnnotation(
      "DM number" = anno_barplot(-ss, 
                                 baseline = 0,
                                 border = FALSE, 
                                 gp = gpar(fill = "cyan",alpha = 0.6), 
                                 width = unit(4, "cm")
      ),
      set_name = anno_text(set_name(m), 
                           location = 0.5, 
                           just = "center",
                           width = max_text_width(set_name(m)) + unit(4, "mm"))
    ), 
    right_annotation = NULL,
    show_row_names = FALSE
  )
  
  ht = draw(ht)
  pdf(paste0(store_path,"/03.DAM_upset.pdf"),width = 6,height = 4)
  ht
  invisible(dev.off())
  
  
  message(msg_run("generate output tables ..."))
  ## output DAM
  
  DAM_compounds = DAM_tbl_all %>% 
    filter(
      abs(log2fc) >= log2fc_cut 
    ) %>% 
    filter(
      pvalue <= pval_cut
    ) %>% 
    filter(
      FDR <= qval_cut
    ) %>% 
    filter(
      VIP >= VIP_cut
    )
  DAM_compounds.anno = DAM_compounds %>% left_join(.,annot_df,by = "CompoundID")
  if(nrow(DAM_compounds) == 0) {
    message(msg_warning("Warning: There is no DAM compounds under the selected cutoff, \nmaybe you should set a more flexible threshold such as ") %+% magenta$bold$italic$underline("< -q 1 -l 0 >"))
   # q(status = 1)
  } else {
    write.csv(x = DAM_compounds,file = paste0(store_path,"/03.DAM_compounds.csv"),row.names = F)
    write.csv(x = DAM_compounds.anno,file = paste0(store_path,"/03.DAM_compounds_annot.csv"),row.names = F)
  }
  
  
  message(msg_run("volcan plot ..."))
  # volcano plot ------------------------------------------------------------
  
  Vocanoplot = function(x,title){
    x %>% 
      mutate(group = case_when(
        pvalue <= pval_cut & VIP >= VIP_cut & log2fc > log2fc_cut & pvalue <= pval_cut ~ "up",
        pvalue <= pval_cut & VIP >= VIP_cut & log2fc < -log2fc_cut & pvalue <= pval_cut~ "down",
        TRUE ~ "not significant"
      ),
      log10pval = -log10(pvalue)
      )-> vocdata
    if(qval_cut <= pval_cut) {yinter = qval_cut} else {yinter = pval_cut}
    p = ggplot(data = vocdata,aes(x = log2fc,y = log10pval))+
      geom_point(aes(color = group,size = VIP))+
      scale_color_manual(values = c("blue","grey","red"))+
      scale_size(range = c(0.05,1))+
      theme_bw()+
      ylab(expression(paste(-log10,("p-value"))))+
      xlab(expression(paste(log2,"(fold change)")))+
      xlim(-max(vocdata$log2fc)-1,max(vocdata$log2fc)+1)+
      ylim(0,max(vocdata$log10pval)+1)+
      ggtitle(title)+
      annotate("text",x = max(vocdata$log2fc)-1,y = max(vocdata$log10pval)-1,
               label = paste0("up regular:",nrow(filter(vocdata,group == "up"))),
               color = "red",size = 3)+
      annotate("text",x = -max(vocdata$log2fc)+1,y = max(vocdata$log10pval)-1,
               label = paste0("down regular:",nrow(filter(vocdata,group == "down"))),
               color = "blue",size = 3)+
      geom_hline(yintercept = -log10(yinter),lty=3,col="black",lwd=0.5)+
      geom_vline(xintercept = log2fc_cut,lty=3,col="black",lwd=0.5)+
      geom_vline(xintercept = -log2fc_cut,lty=3,col="black",lwd=0.5)
    theme_prism(border = T)
    return(p)
  }
  
  pdf(paste0(store_path,"/04.volcano_plot.pdf"),width = 8,height = 5)
  Vocanoplot(x = DAM_tbl_all,title = paste0(left," vs ",right)) 
  invisible(dev.off())
  
  
  # heatmap -----------------------------------------------------------------
  
  message(msg_run("heatmap ..."))
  
  DAM_compounds %>% 
    select("CompoundID") %>% 
    inner_join(.,pca_mat %>% rownames_to_column("CompoundID"),by = "CompoundID") %>% 
    column_to_rownames("CompoundID")-> heat_mat
  
  col_fun = colorRamp2(c(-2, 0, 2), c("blue", "white", "gold"))
  ht_DAM = Heatmap(
    matrix = t(scale(t(heat_mat))),
    show_row_names = F,
    col = col_fun,bottom_annotation = HeatmapAnnotation(
      Sample = data.frame(
        row.names = c(left_index,right_index),
        group = rep(c(left,right),times = c(l_num,r_num))
      ) %>% as.matrix()
    )
  )
  pdf(paste0(store_path,"/05.DAM_heatmap.pdf"),width = 6,height = 9)
  draw(ht_DAM)
  invisible(dev.off())
  message(msg_yes(paste0("Congratulation DAM analysis done! \nplease change directory to \n",getwd(),gsub("./","/",store_path),"\nchecking the result.")))
  x_para = c("sample group 1","sample group 2","log2fc cutoff","pvalue cutoff","FDR cut off","VIP cutoff","heatmap scale method")
  x_value = c(left,right,log2fc_cut,pval_cut,qval_cut,VIP_cut,"Z-score by row")
  if(x_value[3] != 0) {tag_3 = "*"} else {tag_3 = ""}
  if(x_value[4] != 1) {tag_4 = "*"} else {tag_4 = ""}
  if(x_value[5] != 1) {tag_5 = "*"} else {tag_5 = ""}
  if(x_value[6] != 0) {tag_6 = "*"} else {tag_6 = ""}
  tag_1 = ""
  tag_2 = ""
  tag_7 = ""
  x_tmp = c(tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7)
  x_value = paste(x_value,x_tmp)
  out_para = data.frame(
    parameter = x_para,
    value = x_value
  )

  save(Interactive,out_para,pca_result,pca_group,DAM_all,ht,DAM_compounds.anno,DAM_compounds,ht_DAM,file = paste0(store_path,"/DAM_result.rdata"))
  setwd(store_path)
  ## generate report
  rmarkdown::render("../MAD_report.Rmd",
                    rmarkdown::html_document())
}


